version: '3.8'

services:  
  task-manager-app:
    build:
      context: .
      dockerfile: ./dockerfile
    image: task-manager-app
    ports:
      - 80:8080
    depends_on:
      - db


  db:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 9906:3306
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d  